### ISSUE TITLE
Plugin does not recognize functions generated by macro in companion object

### ISSUE THREAD

**Issue by justjoheinz** [spotify/scio-idea-plugin#7] opened 2017-06-13 14:41 UTC
Intellij Version 2017.1.4

Scio Idea Plugin: v0.1.5

Scala Plugin:  2017.1.19

Functions like `schema`or `toTableRow` are still red squiggled. the plugin is `on` as per its settings.

**Comment by ravwojdyla** [comment] 2017-06-13 17:14
Used the same exact versions and can't reproduce this problem, tried together with [scio-template.g8](https://github.com/spotify/scio-template.g8). Also I'm on OS X 10.11.6, and we have other people using this plugin on Linux distros.

**Comment by justjoheinz** [comment] 2017-06-14 08:03
On gitter.im @ravwojdyla posted this code (using the scio.g8 template):

```
package example

import com.spotify.scio.bigquery.types.BigQueryType

object WordCount {

  @BigQueryType.fromQuery(
    """|SELECT kind, phoneNumber
       |FROM `bigquery-samples.nested.persons_living`
    """.stripMargin) class Foo

  def main(cmdlineArgs: Array[String]): Unit = {
    Foo.fromTableRow
    Foo.schema
  }
}
```

This code is not working for me. Foo is not recognized. Compilation works though with `sbt -Dbigquery.project=[someProjectId] compile`

Does this imply that I need to set some properties in Intellij to make it recognize Foo there?

**Comment by ravwojdyla** [comment] 2017-06-14 14:54
@justjoheinz you don't need to add any properties to Intellij (especially if you have gcloud configured with project/auth - according to the wiki). If sbt compilation works fine, try to make some changes around the code (new lines etc), to see if Intellij updates/picks up the context for macros. You could also check the intellij logs at https://github.com/spotify/scio-idea-plugin#logging to see if there is any problem there.

**Comment by ravwojdyla** [comment] 2017-06-27 16:17
Closing this @justjoheinz - can't reproduce. If you want to talk about this - please reach out of gitter, we can also setup a hangout or something similar. Please reopen if needed.

**Closed by ravwojdyla** 2017-06-27 16:17 UTC
Labels: bug

**Comment by justjoheinz** [comment] 2017-06-29 09:19
I finally got around to have a look in the log file of Intellij - this is what I am seeing:

```
2017-06-29 11:12:40,577 [  13235]  ERROR - nsions.impl.ExtensionPointImpl - loader constraint violation: when resolving method "scala.StringContext.<init>(Lscala/collection/Seq;)V" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, com/spotify/scio/ScioInjector, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, scala/StringContext, have different Class objects for the type scala/collection/Seq used in the signature 
com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: loader constraint violation: when resolving method "scala.StringContext.<init>(Lscala/collection/Seq;)V" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, com/spotify/scio/ScioInjector, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, scala/StringContext, have different Class objects for the type scala/collection/Seq used in the signature
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "scala.StringContext.<init>(Lscala/collection/Seq;)V" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, com/spotify/scio/ScioInjector, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, scala/StringContext, have different Class objects for the type scala/collection/Seq used in the signature
	at com.spotify.scio.ScioInjector.<init>(ScioInjector.scala:39)
java.lang.LinkageError: loader constraint violation: when resolving method "scala.StringContext.<init>(Lscala/collection/Seq;)V" the class loader (instance of com/intellij/ide/plugins/cl/PluginClassLoader) of the current class, com/spotify/scio/ScioInjector, and the class loader (instance of com/intellij/util/lang/UrlClassLoader) for the method's defining class, scala/StringContext, have different Class objects for the type scala/collection/Seq used in the signature
	at com.spotify.scio.ScioInjector.<init>(ScioInjector.scala:39)
```

This hints at something which should be easy to fix - if you have an idea, please let me know. Otherwise ping on gitter.im.

**Comment by ravwojdyla** [comment] 2017-06-29 14:26
@justjoheinz `LinkageError` nice. Do you have some kind of custom setup? Which version of scala and scio are you using?
